// lib/urlMappings.ts
export const urlMappings: { [key: string]: string } = {
  "Class 9": "https://example.com/class9",
  "Class 10": "https://example.com/class10",
  "Class 11": "https://example.com/class11",
  "Class 12": "https://example.com/class12",
  "Ujyalo Yatra": "https://drive.google.com/file/d/1Z64lG2ITvfb2aNBJlXrt4K8YhP51wKf6/preview",
  "Ghar Jhagada": "https://drive.google.com/file/d/1YmzXemiF2mBwAGQpPr9hG3QtKWDqrppD/preview",
  "Chikitsa  bigyaan ra Aayurbed Chikitsa": "https://drive.google.com/file/d/1WYSRwc5U01ywQeRUQRnqlDT2vWc2AxYd/preview",
  "Yesto Kailyai Nahos": "https://drive.google.com/file/d/1So0LU5iseStVU3OXqV2WAokLYVQ_S19L/preview",
  "Laxmi Prasad Devkota": "https://drive.google.com/file/d/1iDFuYVKyt5CIUlQ8rc4fOPLfnPedQHkP/preview",
  "Adhikar Thulo ki Kartavya Thulo": "https://drive.google.com/file/d/1v_Se89_ktYBW1loj9-A7KI6-bw-0VA5H/preview",
  "Satru": "https://drive.google.com/file/d/1W6CEj_NIgoikvX2MH_2in_CiNipnHRFk/preview",
  "Nepali Hamro Shram Ra Sip": "https://drive.google.com/file/d/1mGrW8V0jZd0vzFHsrexc8nb9IBYaXAk-/preview",
  "Mero Desh Ko Sikshya": "https://drive.google.com/file/d/1g_zSkdpQIasNTUTInNsFAivq4NFiVvyX/preview",
  "Byabasahik Chithi": "https://drive.google.com/file/d/1AF9vWf6rjNWv09nGYDouY-awzyTwSCzn/preview",
  "Kartabya": "https://drive.google.com/file/d/1AF9vWf6rjNWv09nGYDouY-awzyTwSCzn/preview",
  "Pablo Picasso": "https://drive.google.com/file/d/1VVYPuPeouRdTfgq2Xkd17lot7tpGHRut/preview",
  "Pakhnos!": "https://drive.google.com/file/d/15lL-_dm4Co6WvHXkjvPKojG9dQfiNif_/preview",
  "Introduction to DBMS  Architecture":"https://drive.google.com/file/d/1QU-VaWXieh87FTl6L4IT4lnRKjtShlb3/preview",
  "Entity Relationship Modal":"https://drive.google.com/file/d/1js4TnHdBednI4xrT72J4YSe59Ab7pzVf/preview",
  "Sequencial Query Language (SQL)":"https://drive.google.com/file/d/1UVPe7phWPIhJJefkVxs49SCd0mIk3eKC/preview",
  "Database Design":"https://drive.google.com/file/d/1k6L9n_2JmAHvURO43qLkXGrQ9Hw1mnwI/preview",
"Introduction to Object Oriented Programming":"https://drive.google.com/file/d/1Zu8AmqXZtwHmNcn-eR1OEKZFQGlN_qcP/preview",
};